services:
  caddy:
    container_name: caddy
    image: caddy:2.7.4-alpine
    restart: unless-stopped
    depends_on:
      - php-fpm
      - database
  php-fpm:
    container_name: php-fpm
    build:
      context: .docker/bin/${PHP_VERSION:-php84}
    restart: unless-stopped
    env_file:
      - .env.docker
  database:
    image: mariadb:10.11.4
    container_name: mariadb
    restart: 'always'
    volumes:
      - database_data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_USER: ${MYSQL_USER:-user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-database}
volumes:
  database_data:
